raw_root: data/raw/donnee_cerco/data_raw_fif
out_root: data/processed/preprocessed
hypno_root: data/raw/donnee_cerco/data_raw_fif   

eeg:
  l_freq: 0.5
  h_freq: 80.0
  notch: 50.0

emg:
  hp: 30.0
  lp: 100.0
  notch: 50.0

eog:
  hp: 0.3
  lp: 10.0
  notch: Null

yasa:
  win_sec: 4.0
  method: covar      # ou "std"
  threshold: 3.0
  include: sleep     # sleep / rem / all
