raw_root: /home/darryld/documents/EEG/raw
out_root: /home/darryld/documents/EEG/preprocessed/XAI/data
hypno_root: /home/darryld/documents/EEG/raw   

eeg:
  l_freq: 0.5
  h_freq: 80.0
  notch: 50.0

emg:
  hp: 30.0
  lp: 100.0
  notch: 50.0

yasa:
  win_sec: 4.0
  method: covar      # ou "std"
  threshold: 3.0
  include: sleep     # sleep / rem / all
