stages:

  preprocess:
    cmd: python scripts/preprocess.py --config configs/preproc/default.yaml
    deps:
      - scripts/preprocess.py
      - src/data/preprocessing.py
      - configs/preproc/default.yaml
      - data/raw/
    outs:
      - data/processed/preprocessed/     # <-- Output du preprocessing (à adapter)

  segment_rem:
    cmd: python scripts/segment_rem.py --config configs/preproc/segment_rem.yaml
    deps:
      - scripts/segment_rem.py
      - src/data/preprocessing.py
      - configs/preproc/segment_rem.yaml
      - data/processed/preprocessed/      # <-- dépend du preprocess
    outs:
      - data/processed/rem_epochs/         # <-- ICI seront les fichiers *_REM-epo.fif

  extract_features:
    cmd: python scripts/extract_features.py --config configs/preproc/features.yaml
    deps:
      - scripts/extract_features.py
      - configs/preproc/features.yaml
      - data/processed/rem_epochs/
    outs:
      - data/processed/features/features.csv
